title: Kinnuch
# tagline: Se vínimraef îm. Ballen od Jekyll.
# description: I rennas gwaith ’wen edhelthas.
#Comment out url when working locally to resolve base urls correctly
url: https://kinnuch.github.io

# Owner/author information
owner:
  name: Kinnuch
  avatar: arda.png

  # bio: I rennas gwaith ’wen edhelthas.
  email: 1900017838@pku.edu.cn
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github: Kinnuch

links:
  - title: Barphalt
    url: /
  - title: Laim
    url: /laim/
  - title: Haudhas
    url: /haudhas
  - title: Cerf
    url: /cerf
  - title: Mínimraef
    url: /mínimraef
  - title: TEAE
    url: /teae

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: kinnuch

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]