# Auto-generated vocabulary data
# 819 unique entries
VOCAB = {
    "Aldúya": ("n", "Tuesday, Trees-day"),
    "Anar": ("n", "Sun"),
    "Anarya": ("n", "Sunday"),
    "Cermië": ("n", "July"),
    "Elenya": ("n", "Saturday, Star-day"),
    "Eru": ("n", "The One, God"),
    "Eärenya": ("n", "Thursday, Sea-day"),
    "Hísimë": ("n", "November"),
    "Isil": ("n", "Moon"),
    "Isilya": ("n", "Monday, Moon-day"),
    "Lótessë": ("n", "May"),
    "Menelya": ("n", "Wednesday, Heavens-day"),
    "Narquelië": ("n", "October"),
    "Narvinyë": ("n", "January"),
    "Nárië": ("n", "June"),
    "Nénimë": ("n", "February"),
    "Ringarë": ("n", "December"),
    "Súlimë": ("n", "March"),
    "Valanya": ("n", "Friday, Vala-day"),
    "Víressë": ("n", "April"),
    "Yavannië": ("n", "September"),
    "accal": ("v", "to blaze, shine brilliantly"),
    "aha": ("n", "rage"),
    "ahta": ("v", "to narrow"),
    "ahtar": ("v", "to do back, react"),
    "ahtarië": ("n", "reaction"),
    "ahto": ("n", "wright, maker, craftsman"),
    "ahya": ("v", "to change"),
    "ai": ("interj", "ah, alas"),
    "aicalë": ("n", "peak"),
    "aicassë": ("n", "mountain peak"),
    "aico": ("n", "cliff"),
    "ailin": ("n", "(large) lake, pool"),
    "ailindo": ("n", "loon, lake-singer"),
    "aima": ("pron", "anything, whatever"),
    "aimo": ("n", "saint"),
    "aimë": ("n", "surprise"),
    "aina": ("adj/v", "holy, revered, numinous; to hallow, bless"),
    "ainas": ("n", "shrine, fane, hallow"),
    "aini": ("n", "holy one, angelic spirit (f.)"),
    "aino": ("n", "god"),
    "ainu": ("n", "holy one, angelic spirit (m.)"),
    "aipio": ("n", "cherry"),
    "aiqua": ("adj", "steep"),
    "aiquen": ("pron", "if anybody, whoever"),
    "aira": ("adj", "holy, sanctified"),
    "airalindë": ("n", "hymn, holy song"),
    "airimo": ("n", "priest"),
    "airon": ("n", "ocean"),
    "airë": ("n", "holiness, sanctity"),
    "airëa": ("adj", "holy"),
    "aista": ("v", "to dread"),
    "aita": ("v", "to revere, worship"),
    "aiwë": ("n", "bird"),
    "al(a)": ("prefix", "in-, un-, not"),
    "ala": ("v", "to grow (of plants), plant; to flourish"),
    "alasaila": ("adj", "unwise"),
    "alassë": ("n", "happiness, joy"),
    "alassëa": ("adj", "happy"),
    "alcar": ("n", "glory, splendour, radiance"),
    "alda": ("n", "tree"),
    "alfírima": ("adj", "immortal"),
    "almë": ("n", "good fortune"),
    "alqua": ("n", "swan"),
    "alvë": ("n", "elm"),
    "alya": ("adj", "rich, prosperous"),
    "amba": ("adv/adj", "up, upwards; more"),
    "ambo": ("n", "hill, rising ground"),
    "ambos": ("n", "breast, chest"),
    "ambë": ("adv", "more"),
    "amil(lë)": ("n", "mother"),
    "ampa": ("n", "hook"),
    "ampano": ("n", "building"),
    "amya": ("n", "mummy, (my) mother"),
    "an": ("conj", "for, because"),
    "ana": ("prep", "to, towards"),
    "anca": ("n", "jaws"),
    "anda": ("adj", "long"),
    "ando": ("n", "gate, (great) door"),
    "andúnë": ("n", "sunset, the West"),
    "anga": ("n", "iron"),
    "ango": ("n/u", "snake"),
    "anna": ("n", "gift"),
    "anta": ("v", "to give, present"),
    "anto": ("n", "mouth"),
    "appa": ("v", "to touch"),
    "apsa": ("n", "meat, cooked food"),
    "apta": ("v", "to refuse"),
    "aqua": ("adv", "fully, completely"),
    "ar": ("conj", "and"),
    "ara": ("prep", "beside, next to, by"),
    "aran": ("n", "king"),
    "aranel": ("n", "princess"),
    "aranië": ("n", "kingdom"),
    "arda": ("n", "realm, world"),
    "arin": ("n", "morning"),
    "armar": ("n", "goods (pl.)"),
    "arya": ("adj", "excelling, better"),
    "asarta": ("n", "doctor"),
    "assa": ("n", "hole"),
    "asta": ("n", "month"),
    "asëa": ("n", "healing herb"),
    "atan": ("n", "man, human being"),
    "atar": ("n", "father"),
    "atta": ("num", "two"),
    "atto": ("n", "daddy, father (familiar)"),
    "attëa": ("num", "second (ordinal)"),
    "atyo": ("n", "daddy, (my) father"),
    "au": ("adv", "away, off, not here"),
    "aurë": ("n", "daytime, day"),
    "auta": ("v", "to go away, depart, leave"),
    "avalda": ("adj", "excited"),
    "axo": ("n", "bone"),
    "axë": ("n", "neck (vertebrae), spine"),
    "caima": ("n", "bed"),
    "caimasan": ("n", "bedroom"),
    "caita": ("v", "to lie down; to lay, place"),
    "cala": ("n", "light"),
    "calca": ("n", "glass"),
    "calima": ("adj", "bright"),
    "calma": ("n", "lamp"),
    "canquain": ("num", "forty"),
    "canquë": ("num", "fourteen"),
    "canta": ("n/num", "shape; four"),
    "cantil": ("n", "rectangle"),
    "canya": ("v", "to command"),
    "cap": ("v", "to jump"),
    "car": ("v", "to do, make"),
    "carassë": ("n", "built fort, dwelling with bulwarks"),
    "carasta": ("v", "to build, construct"),
    "caraxë": ("n", "jagged hedge of spikes"),
    "carca": ("n", "fang, tooth, tusk"),
    "carcanë": ("n", "row of teeth"),
    "carda": ("n", "deed, action"),
    "carina": ("adj", "done, made, finished"),
    "cariquetta": ("n", "verb (grammar)"),
    "carië": ("n", "doing, making"),
    "carma": ("n", "tool, implement, weapon"),
    "carmen": ("n", "recipe"),
    "carmë": ("n", "production, making; structure"),
    "carnë": ("adj", "red, scarlet"),
    "carpë": ("n", "hat"),
    "cas": ("n", "head, top"),
    "castol": ("n", "helmet"),
    "cat": ("v", "to shape, fashion"),
    "cav": ("v", "to receive"),
    "celu": ("v", "to flow (forth)"),
    "cemen": ("n", "earth"),
    "cen": ("v", "to see, look"),
    "cendelë": ("n", "face, visage"),
    "cendë": ("n", "point"),
    "ces": ("v", "to search, examine"),
    "cesta": ("v", "to ask"),
    "cirma": ("n", "knife"),
    "cirya": ("n", "ship"),
    "coimas": ("n", "life-bread, lembas"),
    "coirë": ("n", "early spring, stirring"),
    "coita": ("v", "to live (is alive)"),
    "col": ("v", "to carry, bear, wear"),
    "colca": ("n", "box"),
    "collo": ("n", "cloak"),
    "coranar": ("n", "(solar) year, sun-round"),
    "corma": ("n", "ring"),
    "corna": ("adj", "round"),
    "coron": ("n", "globe, ball"),
    "corpë": ("n", "skull"),
    "costa": ("v", "to quarrel"),
    "cotto": ("n", "enemy"),
    "cuivië": ("n", "awakening"),
    "culda": ("adj", "flame-coloured, golden-red"),
    "culuina": ("adj", "orange, golden-red"),
    "culuma": ("n", "orange (fruit)"),
    "cumbo": ("n", "belly"),
    "cumna": ("adj", "empty"),
    "cundo": ("n", "prince"),
    "curuni": ("n", "witch"),
    "curwë": ("n", "craft, skill"),
    "cáno": ("n", "commander"),
    "cárima": ("adj", "feasible, able to be done"),
    "cé": ("adv", "maybe, possibly"),
    "cólima": ("adj", "light, bearable"),
    "cöa": ("n", "house"),
    "cúna": ("v", "to bend"),
    "dac": ("v", "to slay"),
    "dacil": ("n", "slayer"),
    "dactil": ("n", "finger"),
    "ec": ("v", "to have a chance to"),
    "ehtë": ("n", "spear"),
    "ela": ("interj", "behold"),
    "elda": ("n", "elf"),
    "eldë": ("pron", "even you (plural)"),
    "elen": ("n", "star"),
    "elmë": ("pron", "even we (but not you)"),
    "elvë": ("pron", "even we (including you)"),
    "elyë": ("pron", "even you (polite)"),
    "emma": ("n", "picture, image"),
    "en": ("adv", "yonder; then (future)"),
    "enar": ("n", "tomorrow"),
    "endë": ("n", "centre, middle"),
    "endëa": ("adj", "middle"),
    "enenquë": ("num", "sixteen"),
    "engwa": ("adj", "sickly"),
    "enquain": ("num", "sixty"),
    "enquië": ("n", "Elvish week (six days)"),
    "enquë": ("num", "six"),
    "enta": ("adj", "that yonder"),
    "entul": ("v", "to return"),
    "enyal": ("v", "to recall, remember"),
    "enyalië": ("n", "memory"),
    "epetai": ("conj", "consequently"),
    "epë": ("prep", "after (time); before (place)"),
    "er": ("adj", "one, alone"),
    "erdë": ("n", "seed"),
    "eressëa": ("adj", "lonely"),
    "essë": ("n", "name"),
    "esta": ("v", "to name"),
    "estel": ("n", "hope, faith"),
    "et": ("prep", "out (of)"),
    "fairë": ("n", "spirit, phantom"),
    "falassë": ("n", "(wave-beaten) shore"),
    "fanga": ("n", "beard"),
    "fanta": ("v", "to veil, cloak"),
    "fanwa": ("n", "veil, screen"),
    "fanya": ("n", "(white) cloud"),
    "fara": ("v", "to hunt"),
    "faralë": ("n", "hunt"),
    "farna": ("n", "prey"),
    "fasta": ("v", "to please"),
    "felmë": ("n", "emotion"),
    "fendë": ("n", "door"),
    "ferya": ("v", "to ready, prepare"),
    "filit": ("n", "sparrow, small bird"),
    "findë": ("n", "hair (especially of head)"),
    "finwa": ("adj", "dexterous, clever"),
    "finya": ("adj", "clever"),
    "fir": ("v", "to die (naturally)"),
    "firin": ("adj", "dead (naturally)"),
    "formen": ("n", "north"),
    "forya": ("adj", "right (hand)"),
    "fána": ("adj", "white"),
    "fárëa": ("adj", "enough, sufficient"),
    "fëa": ("n", "spirit, soul"),
    "fírië": ("n", "(natural) death"),
    "haira": ("adj", "far, remote"),
    "haiya": ("adv", "far away"),
    "halla": ("adj", "tall"),
    "hampë": ("n", "clothing"),
    "handa": ("adj", "intelligent"),
    "hanquenta": ("n", "answer"),
    "hanquet": ("v", "to answer"),
    "hanta": ("v", "to thank, give thanks"),
    "hanwa": ("n", "chair"),
    "hanya": ("v", "to understand"),
    "harma": ("n", "treasure"),
    "harna": ("v", "to wound"),
    "hasa": ("v", "to treat, cure"),
    "hasta": ("v", "to mar, spoil"),
    "hat": ("v", "to throw"),
    "helca": ("adj", "icy"),
    "helcë": ("n", "ice"),
    "hempa": ("n", "cord, rope"),
    "hen": ("n", "eye"),
    "henta": ("v", "to read, scan"),
    "heri": ("n", "lady"),
    "heru": ("n/v", "lord; to rule"),
    "hesto": ("n", "captain"),
    "hildë": ("n", "heir, follower"),
    "hilya": ("v", "to follow"),
    "hir": ("v", "to find"),
    "hiswa": ("adj", "grey (of weather)"),
    "hlaiwa": ("adj", "sick"),
    "hlar": ("v", "to hear"),
    "hlas": ("n", "ear"),
    "hlic": ("v", "to creep, sneak"),
    "hlívë": ("n", "sickness"),
    "hlón": ("n", "noise, sound"),
    "hresta": ("n", "shore, beach"),
    "hris": ("v", "to snow (impersonal)"),
    "hráva": ("adj", "wild"),
    "hrívë": ("n", "winter"),
    "hröa": ("n", "body"),
    "huo": ("n", "dog"),
    "hwesta": ("n", "breeze"),
    "hya": ("conj/pron", "or; other thing"),
    "hyalin": ("n", "paper"),
    "hyalta": ("v", "to strike, make ring"),
    "hyam": ("v", "to pray"),
    "hyapat": ("n", "shoe"),
    "hyarmen": ("n", "south"),
    "hyarya": ("adj", "left (hand)"),
    "hye": ("pron", "other person"),
    "hó": ("n", "owl"),
    "hón": ("n", "heart (physical)"),
    "hórëa": ("adj", "impulsive"),
    "húna": ("adj", "accursed"),
    "húta": ("v", "to curse"),
    "illumë": ("adv", "always"),
    "ilya": ("adj", "every, each"),
    "ilyë": ("adj", "all (plural)"),
    "imbi": ("prep", "among (pl.)"),
    "imbilat": ("n", "deep valley"),
    "imbë": ("prep", "between"),
    "imlë": ("pron", "yourself (polite)"),
    "immë": ("pron", "ourselves (exclusive)"),
    "imni": ("pron", "myself"),
    "imya": ("adj", "same, identical"),
    "inca": ("n", "idea"),
    "indo": ("n", "(inner) mind, the will"),
    "induinen": ("n", "purpose"),
    "indyo": ("n", "grandson"),
    "indë": ("pron", "yourselves"),
    "indómë": ("n", "will(power)"),
    "inga": ("n", "top"),
    "insa": ("pron", "itself"),
    "insë": ("pron", "himself, herself"),
    "inta": ("pron", "even they (neuter)"),
    "intya": ("n/v", "guess, notion; to guess"),
    "intyë": ("pron", "yourself (familiar)"),
    "intë": ("pron", "even they; themselves"),
    "inwë": ("pron", "ourselves (inclusive)"),
    "inyë": ("pron", "even I"),
    "issa": ("pron", "even it"),
    "issë": ("pron", "even he/she"),
    "ista": ("v", "to know"),
    "lah": ("v", "to kick"),
    "laica": ("adj", "green"),
    "lairë": ("n", "poem; summer"),
    "lala": ("v", "to laugh"),
    "laman": ("n", "animal"),
    "lamba": ("n", "tongue (physical)"),
    "lambë": ("n", "tongue, language"),
    "lango": ("n", "neck, throat"),
    "lannë": ("n", "cloth"),
    "lanta": ("v", "to fall"),
    "lasselanta": ("n", "autumn, leaf-fall"),
    "lassë": ("n", "leaf"),
    "lasta": ("v", "to listen"),
    "lattin": ("n", "window"),
    "latya": ("v", "to open"),
    "lauca": ("adj", "warm"),
    "laupë": ("n", "shirt"),
    "laurëa": ("adj", "golden (light or colour)"),
    "lauta": ("v", "to abound"),
    "lav": ("v", "to lick"),
    "lelya": ("v", "to travel, go"),
    "lempë": ("num", "five"),
    "lep": ("v", "to take"),
    "lepenquain": ("num", "fifty"),
    "lepenquë": ("num", "fifteen"),
    "leper": ("n", "finger"),
    "lerta": ("v", "to be free to"),
    "leuca": ("n", "snake"),
    "lev": ("v", "to move (intr.)"),
    "lilta": ("v", "to dance"),
    "limpë": ("n", "wine"),
    "linda": ("adj", "soft, gentle, light"),
    "lindalë": ("n", "music"),
    "lindo": ("n", "singer"),
    "lindë": ("n", "singing, musical sound"),
    "lingwë": ("n", "fish"),
    "linta": ("adj", "swift"),
    "lir": ("v", "to sing"),
    "liru": ("v", "to sing gaily"),
    "lissë": ("adj", "sweet"),
    "loa": ("n", "(seasonal) year"),
    "locin": ("adj", "bent"),
    "loima": ("n", "mistake"),
    "lopoldë": ("n", "rabbit"),
    "lor": ("v", "to sleep"),
    "lossë": ("n", "snow; blossom"),
    "losta": ("v", "to bloom"),
    "luinë": ("adj", "blue"),
    "lungo": ("adj", "heavy"),
    "luppo": ("n", "lump"),
    "lut": ("v", "to float, sail"),
    "lá": ("prep", "beyond"),
    "lícuma": ("n", "candle"),
    "lírë": ("n", "song"),
    "lómë": ("n", "night"),
    "lórë": ("n", "sleep"),
    "lós": ("n", "inflorescence"),
    "lótë": ("n", "flower"),
    "lú": ("n", "time, occasion"),
    "lúcë": ("n", "enchantment, magic"),
    "lúmequenta": ("n", "history"),
    "lúmë": ("n", "period of time, hour"),
    "lúva": ("n", "bow, bend"),
    "ma": ("adv/pron", "question word (yes/no); something"),
    "macil": ("n", "sword"),
    "mahalma": ("n", "throne"),
    "mahar": ("n", "tradesman, merchant"),
    "mahta": ("v", "to handle, wield; to fight"),
    "mai": ("adv", "well"),
    "maica": ("adj", "sharp"),
    "mailëa": ("adj", "lustful"),
    "maira": ("adj", "admirable, excellent"),
    "maiwë": ("n", "gull"),
    "mal": ("conj", "but"),
    "malina": ("adj", "yellow"),
    "mallo": ("adv", "whence, from where"),
    "malo": ("n", "pollen, yellow powder"),
    "malta": ("n", "gold (metal)"),
    "malumë": ("adv", "when (question)"),
    "man": ("pron", "who"),
    "mana": ("pron", "what"),
    "manan": ("adv", "why"),
    "manca": ("v", "to trade"),
    "manen": ("adv", "how"),
    "manna": ("adv", "whither, to where"),
    "manta": ("v", "to bless"),
    "manë": ("adj", "good (moral)"),
    "mapa": ("v", "to grasp, seize"),
    "maquet": ("v", "to question"),
    "mar": ("v", "to live, dwell"),
    "massë": ("adv", "where"),
    "masta": ("v", "to bake"),
    "mat": ("n/v", "meal; to eat"),
    "matta": ("n", "food"),
    "mauya": ("v", "to compel, force"),
    "maxa": ("v", "to cook"),
    "mecin": ("adv", "please"),
    "mel": ("v", "to love (deeply)"),
    "melda": ("adj", "dear, beloved"),
    "melmë": ("n", "love"),
    "mer": ("v", "to hope, wish, want"),
    "metta": ("n", "ending, end"),
    "mi": ("prep", "in"),
    "min": ("num", "one"),
    "minna": ("prep", "into"),
    "minquë": ("num", "eleven"),
    "minya": ("num", "first (ordinal)"),
    "miqu": ("v", "to kiss"),
    "miquë": ("n", "kiss"),
    "miruvórë": ("n", "mead, nectar-drink"),
    "mirwa": ("adj", "precious, valuable"),
    "miuë": ("n", "cat"),
    "mo": ("pron", "someone"),
    "morco": ("n", "bear"),
    "morna": ("adj", "black"),
    "mornië": ("n", "darkness"),
    "morë": ("adj", "dark"),
    "muina": ("adj", "secret"),
    "mussë": ("adj", "soft"),
    "má": ("n", "hand"),
    "máma": ("n", "sheep"),
    "mána": ("n", "blessing"),
    "már": ("n", "home"),
    "mára": ("adj", "good, useful"),
    "márienna": ("interj", "to happiness (farewell)"),
    "máriessë": ("interj", "in happiness (greeting)"),
    "márië": ("adv", "well, happily"),
    "métima": ("adj", "last, ultimate"),
    "mírë": ("n", "jewel, gem"),
    "mísë": ("adj", "grey"),
    "mól": ("n", "slave"),
    "mólë": ("n", "labour, work"),
    "móna": ("n", "womb"),
    "móta": ("v", "to work, labour"),
    "nac": ("v", "to bite"),
    "nahta": ("v", "to slay, kill"),
    "naica": ("adj", "painful"),
    "naicë": ("n", "pain"),
    "naina": ("v", "to lament"),
    "nairë": ("n", "sorrow, lament"),
    "nairëa": ("adj", "sad, sorrowful"),
    "naitië": ("adv", "indeed, truly"),
    "naitë": ("adj", "true"),
    "namba": ("n/v", "hammer; to hammer"),
    "namárië": ("interj", "farewell"),
    "nandë": ("n", "harp"),
    "nat": ("n", "thing"),
    "naxa": ("adj", "sour"),
    "nehtë": ("n", "honey"),
    "neldë": ("num", "three"),
    "neldëa": ("num", "third (ordinal)"),
    "nelet": ("n", "tooth"),
    "nelquain": ("num", "thirty"),
    "nelquë": ("num", "thirteen"),
    "nem": ("v", "to seem, appear"),
    "nenda": ("adj", "wet"),
    "nengwë": ("n", "nose"),
    "nertë": ("num", "nine"),
    "nessa": ("adj", "young"),
    "net": ("v", "to get, obtain"),
    "neterquain": ("num", "ninety"),
    "neterquë": ("num", "nineteen"),
    "nieninquë": ("n", "snowdrop"),
    "nilmë": ("n", "friendship"),
    "ninquë": ("adj", "white, chill"),
    "niqu": ("v", "to be cold, freeze"),
    "nir": ("v", "to press, push"),
    "nié": ("n", "tear"),
    "nor": ("v", "to run"),
    "norna": ("adj", "hard, tough"),
    "norta": ("v", "to ride, (lit.) make run"),
    "not": ("v", "to count"),
    "nu": ("prep", "under, beneath"),
    "nurta": ("v", "to hide"),
    "nut": ("v", "to tie, bind"),
    "nwalmë": ("n", "torment"),
    "nyar": ("v", "to tell, recite"),
    "nyarro": ("n", "rat"),
    "nyellë": ("n", "bell"),
    "nyárë": ("n", "tale, account"),
    "ná": ("interj/v", "yes, it is so; to be"),
    "nárë": ("n", "fire"),
    "násië": ("interj", "amen, may it be so"),
    "néca": ("adj", "pale, dim"),
    "nén": ("n", "water"),
    "nér": ("n", "man (male person)"),
    "nís": ("n", "woman (female person)"),
    "nísima": ("adj", "fragrant"),
    "nó": ("prep", "before (time); at back of (place)"),
    "nóloa": ("n", "yesteryear"),
    "nólë": ("n", "lore, knowledge"),
    "nómë": ("n", "place"),
    "nótë": ("n", "number"),
    "nöa": ("n", "yesterday"),
    "núlë": ("n", "sorcery"),
    "númen": ("n", "west"),
    "núro": ("n", "servant"),
    "ohta": ("n", "war"),
    "ohtar": ("n", "warrior"),
    "ohtë": ("n", "egg"),
    "oialë": ("adv", "forever"),
    "ola": ("v", "to become, grow"),
    "olor": ("n", "dream"),
    "olva": ("n", "plant"),
    "omentië": ("n", "meeting"),
    "ondo": ("n", "rock, stone (as material)"),
    "onta": ("v", "to beget, create"),
    "or": ("prep/v", "above, over; to urge"),
    "orco": ("n/u", "orc, goblin"),
    "ornë": ("n", "(tall) tree"),
    "oromar": ("n", "lofty hall"),
    "oron": ("n", "mountain"),
    "orta": ("v", "to raise, lift up"),
    "orva": ("n", "apple"),
    "orya": ("v", "to rise"),
    "otoquain": ("num", "seventy"),
    "otoquë": ("num", "seventeen"),
    "otso": ("num", "seven"),
    "otsola": ("n", "week (seven days)"),
    "otsëa": ("num", "seventh (ordinal)"),
    "paluhta": ("n", "table"),
    "par": ("v", "to learn"),
    "parca": ("adj", "dry"),
    "parma": ("n", "book"),
    "pas": ("v", "to smooth"),
    "pasta": ("adj", "smooth"),
    "pata": ("v", "to walk"),
    "pempë": ("n", "lip"),
    "pen": ("v", "to lack"),
    "penya": ("adj", "lacking, poor"),
    "perya": ("v", "to halve"),
    "peu": ("n", "lips (as a pair)"),
    "pilin": ("n", "arrow"),
    "pimpë": ("n", "tail"),
    "pirë": ("n", "toe"),
    "poco": ("n", "bag"),
    "poica": ("adj", "clean, pure"),
    "poita": ("v", "to clean"),
    "pol": ("v", "can, to be able to"),
    "porocë": ("n", "chicken"),
    "pusta": ("v", "to stop"),
    "pé": ("n", "(closed) mouth"),
    "pí": ("n", "small insect"),
    "quainëa": ("num", "tenth (ordinal)"),
    "qual": ("v", "to die"),
    "qualin": ("adj", "dead"),
    "qualmë": ("n", "death (agony)"),
    "quanta": ("adj/v", "full; to fill"),
    "quel": ("v", "to fade"),
    "quellë": ("n", "late autumn, fading"),
    "quenta": ("n", "story, narrative"),
    "quer": ("v", "to turn"),
    "quessë": ("n", "feather"),
    "quet": ("v", "to say, speak"),
    "quetta": ("n", "word"),
    "quilta": ("n", "belt"),
    "quilë": ("n", "colour"),
    "quilëa": ("adj", "coloured"),
    "quinga": ("n", "bow (for shooting)"),
    "quácë": ("n", "frog"),
    "quëa": ("n", "vegetable"),
    "quëan": ("num", "ten"),
    "rac": ("v", "to break"),
    "raf": ("v", "to snatch"),
    "rainë": ("n", "peace"),
    "raiqua": ("adj", "angry"),
    "raita": ("v", "to smile"),
    "ramba": ("n", "wall"),
    "ranco": ("n", "arm"),
    "rassë": ("n", "horn (of animal)"),
    "rauco": ("n", "demon"),
    "rauro": ("n", "lion"),
    "raxë": ("n", "danger"),
    "rehta": ("v", "to rescue, save"),
    "remba": ("v", "to net, trap"),
    "rembë": ("n", "net"),
    "rer": ("v", "to sow"),
    "resta": ("n", "field (tilled)"),
    "rimbë": ("n", "host, crowd"),
    "rindë": ("n", "circle"),
    "ringa": ("adj", "cold"),
    "ringë": ("n", "cold (noun)"),
    "rië": ("adv", "only"),
    "rocco": ("n", "horse"),
    "roita": ("v", "to pursue, chase"),
    "rongo": ("adv", "soon"),
    "ronyo": ("n", "hunting dog"),
    "ruhta": ("v", "to terrify"),
    "rusco": ("n/u", "fox"),
    "rá": ("prep", "on behalf of"),
    "ráca": ("n", "wolf"),
    "ráma": ("n", "wing"),
    "ré": ("n", "day (24 hours)"),
    "róma": ("n", "horn (musical instrument)"),
    "rómen": ("n", "east"),
    "saila": ("adj", "wise"),
    "sairon": ("n", "wizard"),
    "salquë": ("n", "grass"),
    "sam": ("v", "to have, possess"),
    "sambë": ("n", "room, chamber"),
    "sana": ("adj/v", "that (previously mentioned); to think"),
    "sanar": ("n", "mind, thinker"),
    "sanda": ("n", "shield"),
    "sanwë": ("n", "thought"),
    "sap": ("v", "to dig"),
    "sar": ("n", "(small) stone, pebble"),
    "sarmë": ("n", "writing"),
    "saura": ("adj", "stinking, vile"),
    "sav": ("v", "to believe"),
    "senya": ("adj", "usual"),
    "ser": ("v", "to rest, tarry; to sew"),
    "sercë": ("n", "blood"),
    "serindë": ("n", "seamstress"),
    "sillë": ("adv", "like this"),
    "silmë": ("n", "starlight"),
    "silo": ("adv", "hence, from here"),
    "silumë": ("adv", "this time"),
    "simpa": ("n", "flute"),
    "sin": ("pron", "this"),
    "sina": ("adj", "this"),
    "sinda": ("adj", "grey"),
    "sinen": ("adv", "by this means"),
    "sinna": ("adv", "to here, hither"),
    "sinomë": ("adv", "here, this place"),
    "sinwa": ("adj", "known, certain"),
    "sirya": ("v", "to flow"),
    "sissë": ("adv", "here"),
    "sië": ("adv", "thus, so"),
    "soron": ("n", "eagle"),
    "sorya": ("v", "to be afraid"),
    "sossë": ("n", "fear"),
    "sulpa": ("v", "to lap up"),
    "sundo": ("n", "base, root, foundation"),
    "sá": ("interj", "yes, I agree"),
    "sára": ("adj", "bitter"),
    "sérë": ("n", "rest, repose"),
    "sí": ("adv", "now"),
    "síma": ("n", "imagination"),
    "síra": ("n", "today"),
    "sís": ("adv", "here"),
    "sítë": ("adv", "of this sort"),
    "sívë": ("prep", "as, this like"),
    "sú": ("n", "sound of wind"),
    "súlë": ("n", "breath; (movement of) spirit"),
    "súma": ("n", "bosom"),
    "ta": ("pron", "that"),
    "tac": ("v", "to fasten, fix"),
    "tallë": ("adv", "like that"),
    "talo": ("adv", "thence, from there"),
    "talta": ("v", "to collapse, fall down"),
    "talumë": ("adv", "that time"),
    "tama": ("pron", "that matter"),
    "tamba": ("v", "to knock, tap"),
    "tambë": ("prep", "so, that like"),
    "tamin": ("n", "forge"),
    "tamma": ("n", "tool"),
    "tamo": ("n", "smith, builder"),
    "tana": ("adj/v", "that; to show, indicate"),
    "tanca": ("adj", "firm, fixed, sure"),
    "tancal": ("n", "brooch, pin"),
    "tanen": ("adv", "in that way"),
    "tanna": ("adv", "thither, to there"),
    "tanomë": ("adv", "there, that place"),
    "tar": ("n", "honorific (sir, madam)"),
    "tarwa": ("n", "garden"),
    "tassë": ("adv", "there"),
    "taxë": ("n", "nail"),
    "tec": ("v", "to write"),
    "tecil": ("n", "pen"),
    "tehta": ("n", "written mark, sign"),
    "tel": ("n", "end (spatial)"),
    "telco": ("n", "leg, stem"),
    "telda": ("adj", "last, final"),
    "tellë": ("n", "rear"),
    "telpë": ("n", "silver, money"),
    "telumë": ("n", "roof, canopy"),
    "telya": ("v", "to finish, complete"),
    "tengwa": ("n/v", "letter (of the alphabet); to read (writing)"),
    "tennoio": ("adv", "forevermore"),
    "tensi": ("adv", "still, up until now"),
    "tenta": ("adv", "yet, up until then"),
    "ter": ("prep", "through"),
    "termar": ("v", "to endure, last"),
    "tev": ("v", "to hate"),
    "tillë": ("n", "tip, point"),
    "tinco": ("n", "metal"),
    "tinta": ("v", "to kindle, light"),
    "tir": ("v", "to watch, guard"),
    "tirion": ("n", "watch tower"),
    "tië": ("n", "road, path, way"),
    "toldo": ("num", "eight"),
    "tolquain": ("num", "eighty"),
    "tolquë": ("num", "eighteen"),
    "tompa": ("n", "drum"),
    "tuc": ("v", "to pull, draw"),
    "tuia": ("v", "to sprout, bud"),
    "tuilë": ("n", "spring (season), budding"),
    "tul": ("v", "to come"),
    "tulma": ("n", "event, occurrence"),
    "tumna": ("adj", "low, deep"),
    "tur": ("v", "to conquer, rule, master"),
    "turca": ("adj", "strong (physically)"),
    "turu": ("v", "to master, defeat"),
    "tyal": ("v", "to play"),
    "tyalië": ("n", "play, mirth, sport"),
    "tyar": ("v", "to cause"),
    "tyaro": ("n", "doer, agent"),
    "tyav": ("v", "to taste"),
    "tyellë": ("n", "grade, step, level"),
    "tyelpë": ("n", "silver (archaic)"),
    "tyávë": ("n", "taste"),
    "tá": ("adv", "then (past)"),
    "tál": ("n", "foot, bottom"),
    "tára": ("adj", "high, lofty"),
    "tári": ("n", "queen"),
    "tárië": ("n", "height"),
    "téma": ("n", "series, row, line"),
    "tó": ("n", "wool"),
    "tóa": ("n", "wood (as material)"),
    "tópa": ("n", "roof"),
    "uhta": ("v", "to dislike"),
    "ui": ("interj/v", "no (it is not so); to not be, not exist"),
    "ul": ("v", "to rain (impersonal)"),
    "ulca": ("adj", "evil, bad"),
    "ulo": ("n", "rain"),
    "ulya": ("v", "to pour"),
    "umbar": ("n", "fate, doom"),
    "undu": ("adv", "down, beneath"),
    "undómë": ("n", "twilight, dusk"),
    "ungwë": ("n", "spider's web"),
    "unquë": ("n", "a hollow"),
    "urra": ("adj", "bad"),
    "urulócë": ("n", "(fire) dragon"),
    "vacco": ("n", "jacket"),
    "vala": ("n", "divine being, angelic power"),
    "vanda": ("n", "oath, pledge"),
    "vanima": ("adj", "beautiful, fair"),
    "vanwa": ("adj", "lost, gone, departed"),
    "varna": ("adj", "safe, protected"),
    "varni": ("adj", "brown"),
    "varya": ("v", "to protect, defend"),
    "ve": ("prep", "as, like"),
    "verya": ("adj/v", "brave, bold; to dare"),
    "vilya": ("n", "air, sky"),
    "vinya": ("adj", "new, young, fresh"),
    "virya": ("v", "to change (intr.)"),
    "vista": ("n/v", "air (as a substance); to change (something)"),
    "voronda": ("adj", "faithful, loyal"),
    "voronwë": ("n", "faith, loyalty"),
    "vá": ("interj", "no (I won't)"),
    "vá(n)": ("interj", "(I) won't"),
    "váquet": ("v", "to forbid, refuse"),
    "vára": ("adj", "dirty, soiled"),
    "véla": ("adj", "alike, similar"),
    "vëa": ("adj", "seeming, apparent"),
    "ya": ("pron", "that, which (relative)"),
    "yaimë": ("n", "wail, wailing"),
    "yaimëa": ("adj", "wailing"),
    "yal": ("v", "to summon, call"),
    "yanta": ("n", "bridge"),
    "yarra": ("v", "to growl, snarl"),
    "yaxë": ("n", "cow"),
    "ye": ("pron", "who, that (personal relative)"),
    "yermë": ("n", "sexual desire"),
    "yesta": ("n", "beginning, start"),
    "yo": ("conj", "both ... and"),
    "yuhta": ("v", "to use, employ"),
    "yul": ("v", "to drink"),
    "yulda": ("n", "drink, draught"),
    "yulma": ("n", "cup, drinking vessel"),
    "yunquë": ("num", "twelve"),
    "yuquain": ("num", "twenty"),
    "yá": ("conj", "when"),
    "yára": ("adj", "old, ancient"),
    "yávië": ("n", "autumn, harvest"),
    "yávë": ("n", "fruit"),
    "yé": ("interj", "lo, behold"),
    "yén": ("n", "Elvish long year (144 solar years)"),
    "yú": ("adv", "too, also"),
    "yúyo": ("adj", "both"),
    "Ëa": ("n", "Existence, the Universe"),
    "Úrimë": ("n", "August"),
    "ála": ("particle", "do not (prohibition)"),
    "áva": ("interj", "don't (negative imperative)"),
    "ëa": ("v", "to exist"),
    "ëar": ("n", "sea, great sea"),
    "ëaruilë": ("n", "seaweed"),
    "írë": ("n", "desire"),
    "óa": ("adv", "away"),
    "óla": ("v", "to dream (impersonal)"),
    "óma": ("n", "voice"),
    "órë": ("n", "heart (inner mind), conscience"),
    "únótima": ("adj", "numberless, uncountable"),
    "úra": ("adj", "hot (unpleasantly)"),
    "úrë": ("n", "heat"),
    "úsië": ("adv", "on the contrary"),
    "úvanima": ("adj", "ugly"),
    "vanya": ("adj", "beautiful, fair"),
    "vendë": ("n", "maiden, virgin"),
    "massa": ("n", "bread"),
    "mornë": ("adj", "dark, black"),
    "nís": ("n", "woman"),
    "nér": ("n", "man (adult male)"),
    "yávë": ("n", "fruit"),
    "sírë": ("n", "river"),
    "taurë": ("n", "forest"),
    "osto": ("n", "city, fortress"),
    "heru": ("n", "lord, master"),
    "heri": ("n", "lady"),
    "aran": ("n", "king"),
    "tári": ("n", "queen"),
    "ohtar": ("n", "warrior"),
    "rocco": ("n", "horse"),
    "nauco": ("n", "dwarf"),
    "ñoldo": ("n", "Noldo, one of the wise"),
    "rá": ("n", "lion"),
    "nén": ("n", "water"),
    "cala": ("n", "light"),
    "lómë": ("n", "night, dusk"),
    "aurë": ("n", "day, sunlight"),
    "arda": ("n", "realm, region"),
    "cemen": ("n", "earth, soil"),
    "vilya": ("n", "air, sky"),
    "nárë": ("n", "fire, flame"),
    "ondo": ("n", "stone, rock"),
    "alda": ("n", "tree"),
    "lótë": ("n", "flower"),
    "parma": ("n", "book"),
    "macil": ("n", "sword"),
    "anca": ("n", "jaw, fang"),
    "ramba": ("n", "wall"),
    "fëa": ("n", "spirit, soul"),
    "hröa": ("n", "body"),
    "indo": ("n", "heart, mind"),
    "óma": ("n", "voice"),
    "hen": ("n", "eye"),
    "lamba": ("n", "tongue"),
    "tál": ("n", "foot"),
    "ranco": ("n", "arm"),
    "cas": ("n", "head"),
    "lírë": ("n", "song"),
    "quetta": ("n", "word"),
    "tengwa": ("n", "letter, sign"),
    "lambë": ("n", "language, tongue"),
    "nolmë": ("n", "knowledge, lore"),
    "alcar": ("n", "glory, splendour"),
    "estel": ("n", "hope, trust"),
    "melda": ("adj", "beloved, dear"),
    "alta": ("adj", "great, large"),
    "pitya": ("adj", "small, little"),
    "sinda": ("adj", "grey"),
    "ninquë": ("adj", "white"),
    "carnë": ("adj", "red"),
    "laica": ("adj", "green"),
    "lúnë": ("adj", "blue"),
    "malina": ("adj", "yellow"),
    "varna": ("adj", "safe, protected"),
    "halla": ("adj", "tall"),
    "tiuca": ("adj", "thick, fat"),
    "linta": ("adj", "swift, quick"),
    "saila": ("adj", "wise"),
    "verya": ("adj", "bold, daring"),
    "tulca": ("adj", "firm, strong"),
    "mel": ("v", "to love"),
    "cen": ("v", "to see"),
    "hlar": ("v", "to hear"),
    "quet": ("v", "to say, speak"),
    "tec": ("v", "to write"),
    "ista": ("v", "to know"),
    "pol": ("v", "to be able, can"),
    "mer": ("v", "to wish, want"),
    "lir": ("v", "to sing"),
    "nor": ("v", "to run"),
    "cap": ("v", "to leap"),
    "hat": ("v", "to break"),
    "tur": ("v", "to rule, govern"),
    "har": ("v", "to sit, dwell"),
    "ser": ("v", "to rest"),
    "sam": ("v", "to have"),
    "anta": ("v", "to give"),
    "mapa": ("v", "to seize, grasp"),
    "lanta": ("v", "to fall"),
    "nurta": ("v", "to hide"),
    "tulta": ("v", "to summon"),
    "cenda": ("v", "to read, study"),
}
