// 贝烈瑞安德全图 210×150 —— 由 tools/gen-beleriand.mjs 生成，请勿手改
// 要调整地理，改生成器里的地理描述后重跑：node tools/gen-beleriand.mjs
//
// 地形字符：R道路 P草原 F农地 W荒原 T森林 H丘陵 M山地 S沼泽 D浅滩 V河流 O海洋

export const BELERIAND = {
  id: 'beleriand',
  name: '贝烈瑞安德',
  era: 1,
  w: 210, h: 150,
  rows: [
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   0
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   1
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   2
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   3
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   4
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   5
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   6
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   7
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   8
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //   9
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //  10
    'OOOOOOOOOOOOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //  11
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //  12
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //  13
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //  14
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', //  15
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPMMMMMWWWWWWWWFFFFFPPPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPWRWWWWWWWWWWWWWWPPPWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWPPWWWWWWWWWWWWWPPPPPPPPMMMMMMMMMMMMMMM', //  16
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPMMMMMMMMMMMMMMFFFFPPPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRWWWWWWWWWWWWWPPPPPPWHWWHWWWWWWWWWWWWWWWWPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPMMMMMMMMMMMMMMMM', //  17
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMPPWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRWWWWHWWWHHPPPPHPPPHHPWHWWWHHHWWWWWWWWWWWPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPMMMMMMMMMMMMMMMM', //  18
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRWWTWTWWHWPPHPHHHPHHHHHWHHHWHHWHWHTWWWWWPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMMPMMMM', //  19
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTRWWWTTWHWHWHHHPHHHHHHHHHWHHHHWHWHHWWTWWPPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMPPPPPP', //  20
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRWTTTWHWHHHHHHHPHHHHHHHHHHWHHHHHHHWWTTPPPPPPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMPPPPPP', //  21
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWTWTTTRTTTTTHHHHHHHHHHHHHHHHHHHHHHHHHHHHWTPPPPPTTPPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMMPPPPP', //  22
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWTTTRTWTTHHHHHHHHHHHHHHHHHHHHHHHHHHHHHTTTTPPTPTPTPPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMMPPPPP', //  23
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWTWTTTTTRTTHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHTTTTTTTTTPPTPPPPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMMPPPPP', //  24
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWTWTTTTTTTTRTHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHTTTTTTTTTTTTPTPFWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMMPPPPP', //  25
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMWWPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWTTTTTTTTRTTHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHTTTTTTTTTTTTPPFWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPMMMMMMMMMMMPPPPP', //  26
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMWWWPPPPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMMMPPWWWWWHWWWTTTTTTTTRTTTTTTHHHHHHHHHHHHHHHHHHHHHHHHHHHTTTTTTTTTTPTTTFWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPMMMMMMMMMMMPPPPP', //  27
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMWWWPPPPPPPPPPPPPPPWWWMMMMMMMMMMMMMMMMMMMMPPPVVVWWWHHHHHHHTTTRTTTTTTTHHHHHHTTTTHHHHHHHHHHHHHHHHTTTTTTTTTTTTFFWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMPPPPP', //  28
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMWWWWPPPPPPPPPPPPPPPWWWWWMMMMMMMMMMMMMMMMMMFPVVVVHHHHHHHHHHHTTRTTTTTTTTHHHHHTTTTHHHHHHHHHHHHHHHTTTTTTTTTTTTTTTTWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMPPPPP', //  29
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMWWWWPPPHHHHHHHHHHPPFFWWWWWWWMMMMMMMMMMMMMMFFVVVVVWHHHHHHHHHTRRTTTTTTTTTHHHTTTTTTHHHHHHHHHHHHHHHTTHTTTTTTTTTTFTWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPMMMMMMMMMMMPPPPP', //  30
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPWWPPPPPHHHHHHHHHHPPFFFFFWWWWWMMMMMMMMMMMMMFFVVVHVWHHHHHHHHHRRTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHHHHHHTTTTTTTTTTTWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPMMMMMMMMMMMMPPPP', //  31
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPPPPHHHHHHHHHPPPFFFFWWWWWWWWMMMMMMMMMMFFVVVVVHHHHHHHHHRRHTTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHHHHTTTTTTTTTTTFWWWWWPPWWWWWWWWWWWWWWWWPPPWWWWWWWWWWWWWWWWPPPPPMMMMMMMMMMMMPPPP', //  32
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPPFFFHHHHHHHPPPPPFFFFWWWWWWWWFMMMMMMMMFFVVVVVVHHHHHHHHRHHTTTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHHHTTTTTTTTTTWWWFWFPPPPPPPPPPPPPPPPPPPPPPPWWWWWWWWWWWWWWWWPPPPWMMMMMMMMMMMPPPP', //  33
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPFFFFFFHHHHPPPPPPPPPPPWWWWWWFFFFWMMMMMFFVVVVVVHHWHHHHHRHHTTTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHHHTTTTTTTWTTTWWWWPPPPPPFFFFFFPPPPPPPPPPPPWWWWWWWWWWWWWWWWWPWWWMMMMMMMMMMMPPPP', //  34
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPFFFFFFFFFFPPPPPPPPPPPPWWWWWFFFFWMMMMMFFVVVVVVPPPPHHHHRHHTTTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHHHTTTTTTTTTTWWWWWPPPPPFFFFFFFFHPPPPPPPPPPPWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMPPP', //  35
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPFFFFFFFFFFFFPVPPVPPPPPPPPPPFFFFFFMMMMMFFFVVVVVPPPHPHPHRHTTTTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHHTTTTTTPPPPPPPPPPPPHPHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMPPPP', //  36
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPFFFFFFFFFFFVVVVPVPPPPPPPPPPPFFFFFMMMMMFFFFVVVFPPPHHHHRRHPTTTTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHTTTTTTPTPPPPPPPHPHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMMPPP', //  37
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPFFFFFFVVVVVVVVPVPVVVPVPPPPPPPFFFFFMMMMFFFFVVVFPPPPHPRRHPPTPPTTPTTTPTTTTTTTTTTTTTHHHHHHPHHPHTTPTTTHTHHHHPPPHPHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMMPPP', //  38
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPFFFFVFFVVVVVVVVVVVVVVVPVPPPPPPFFFFMMMMFFFFVVVFPPPPPRRHHHTTTPTTPTTTTTPTTPTTTTTTTTHHHHHPHHTTHHHTHTHHTHHHHHPPPPHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMPPP', //  39
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPFFFFVVVVVVVVVVVVVVVVVVVPPPPPPPFFFMMMMFFFVVVVVPPPPRRHHHHHTHHHTHHTTTTTTPTTPTTPTPPTTHHTHTHHHHHTHHHHHHHHHHHHPHHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMPPP', //  40
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPFFFFVVVVVVDDDDDDDDDDDDDRRRRRRRRRRMMMMRRRRDDDDRRRRRHHHHHHHHHHHHHHHHHHHHHTHHHHTTHHHHHHHTTHHHHHHHHHHHHHHHHPPHHHHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMPPP', //  41
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPPFFVVVVVVDDVVVVVVVVVVVVVPPPPPPPPPMMMMPPFFVVVVVPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPHHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMPPP', //  42
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPPVPVVVVVDDVVVVVVVVVVVMVPMMPPPPPPMMMMMPPPPVVVVVPPPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPHHHHHHHHHHHHHHHHHHHHHPPPPPPPPFFFFPPPPPPPPPPPPPMMMMMMMMMMMPPP', //  43
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPPPPPPPPVVVVVDVVVVVVVVVVVMMMMPMMMPPPFMMMMMPPPPVVVVVPPPPPPPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPHHHHHHHHHRHHHHHHHHPPPPPPPPPPFFFFFFPPPPPPPPPPPPMMMMMMMMMMMPPP', //  44
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPHPPPPPPVVVVVVVVVVVVVVMMMVMMMMMMMPMMFMMMMMPPPPVVVVVPPPPPPPPPPPPPPPPPHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPHHHHHHHRRHHHHHHPHPPPPPPPPFFFFFFFFPPPPPPPPPPPMMMMMMMMMMMPPP', //  45
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPHHHPPPPVVVVFVVVVVVVMVMMMMMMMMMMMMMMMFMMMMPPPPPVVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHHPHHHHHRRHHHPPPPPPPPPPPPFFFFFFFFPPPPPPPPPPPMMMMMMMMMMMPPP', //  46
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPHHHHHFPPPFVVVVFVPVMMMMMMMMMMMMMMMMMMMMMMMMMMMVVVVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHPHHHHFRRPHHPPPPPPPPPPPFFFFFFFFPPPPPPPPPPPMMMMMMMMMMMPPP', //  47
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPPHHHHHFFFPPFVFFPVMMMMMMMMMMMMMMMMMMMMMMMMMMMMMVVVVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFPPPPPPPPPPPPPPPPPPPPPPHPHRHHPPPPPPPPPPPPFFFFFFFFPPPPPPPPPPPMMMMMMMMMMMPPP', //  48
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPFHHHHHFFFFPPPPPPPMMMMMMMMMMMFFMMMMMMMMMMMMMMMMVVVVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPRPFFFFPPPPPPPPPPFFTTTFPPPPPPPPPFFFFMMMMMMMMMMMPP', //  49
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMPFHHHHHFFFFPPPPPPMMMMMMMMFMFFFFFMFPMMMMMMMMMMMMVVVVVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPRFFFFFFPPPPPPPPPPTTTTPPPPPPPPPFFFFFMMMMMMMMMMMPP', //  50
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMFFHHHHHFFFFFPPPMPMMMMMMMFFFFFFFFFFPMMMMMMMMMMMMDDDDDDFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTPPPTPPPFTFFFFPPPPPPPPPPPPPPPPPPPPPPPPRFFFFFFFPPPPPPPPPTTTTPPPPPPPPFFFFFFMMMMMMMMMMMPP', //  51
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMFHHHHHFFFFFPPPPPMMMMMMFFFFFFFFFFFPPMMMMMMMMMMMMVVVVVFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTPTPPTPPPTFFFFFPPPPPPPPPPPPPPPPPPPPPPPPRFFFFFFFPPPPPPPPPTTPPPPPPPPPFFFFFFFMMMMMMMMMMMPP', //  52
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMFHHHHHFFFFFPPPMMMMMMMMFFFFFFFFFFFPPPMMMMMMMMMMMVVVVVFPPPPPPPPPPPPPPPPPPPPPPTTPPPTPPTTPTTTPTPTTPTFTFPTPPPPPPPPPPPPPPPPPPPPPPPRFFFFFFFPPPPPPPPPPPPPPPPPPPFFFFFFFFMMMMMMMMMMMPP', //  53
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMHHHHHHFFFFPPPPMMMMMMFFFFFFFFFFFFPPPMMMMMMMMMMFDDDDDFPPPPPPPPPPPPPPPPPPPPPPTPTPTTTTTTTTTPPTPPPPTPPPPPTPPPPPPPPPPPPPPPPPPPPPPRFFFFFFFPPPPPPPPPPPPPPPPPPPFFFFFFFFMMMMMMMMMMMMP', //  54
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMHHHHHHFFFPPPPMMMMMMMFFFFFFFFFFFFPPPMMMMMMMMMMFVVVVVPPPPPPPPPPPPPPPPPPPPTTPPTTTTPPTTPTTTTTTPPTTTTTPTPPTPTPPTFFFPPPPPPPPPPPPPRFFFFFFPPPPPPPPPPPTTTTTTTTTTTTTTTTTMMMMMMMMMMMMP', //  55
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPMMMMMMMMMMMHHHHHHHFFPPPPPMMMMMMMFFFFFFFFFFPPPPMMMMMMMMMMPVVVVVPPPPPPPPPPPPPPPPPPPPTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPFFTFFFPPPPPPPPPPPRRPFFFFPPPPPPPPPPPPTTTTTTTTTTTTTTTTTMMMMMMMMMMMMP', //  56
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMPHHFHHHHHPPPPHMMMMMMMMFFFFFFFFFPPPPMMMMMMMMMMMPVVVVVPPPPPPPPPPPPPPPTPPTTPTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTTPTTFFFFFPPPPPPPPPPRRPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTMMMMMMMMMMMP', //  57
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMFPPFFHHHHHPHHHHMMMMMMMFFFFFFFFPPPPPMMMMMMMMMMPVVVVVVPPPPPPPPPPPPPPPPTPTTPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFTFFFFPPPPPPPPPRRPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTMMMMMMMMMMMP', //  58
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMFFPPPPHHHHHHHHHMHMMMMMMMFFFFFPPPPMMMHHHMMMMMMPVVVVVPPPPPPPPPPPPPTPPTTTVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFFFPPPPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTMMMMMMMMMMMP', //  59
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMFFFPPPHHHHHHHHHHHHMMMMMMMMMPMMPMMMMMHHHMMMMMPPVVVVVPPPPPPPPPPPPPPPPTTVVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTPPPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTRMMMMMMMMMMMP', //  60
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMFFPPPPPPPPPPPPPPPPMMMMMMMMMMMMMMMMMHHHMMMMPPPVVVVVPPFFFFPPPPPPPPPTPTTVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTPTPPPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTRDMMMMMMMMMMMP', //  61
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPMMMMMMMMMMFFPPPPPPPPPPPPPPPMMMMMMMMMMMMMMMMMMMMMMMMMPPPVVVVVPFFFFFFPPPPPPPPPTTTTVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTPPPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTVDDTMMMMMMMMMMMP', //  62
    'OOOOOOOOOOOOOOOOOOOOOPPSSSSSSPPPPFFFFMMFFPPPPPPPPPPPPPPPMPMMMMMMMMMMMMMMMMMMMMMMMPPPVVVVVPFFFFFFPPPPPPPTPTTTTVVVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTVDDTTTMMMMMMMMMMP', //  63
    'OOOOOOOOOOOOOOOOOOOOOPPSSSPPPPPPPPFFFMMFPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMMMMMMMMMPPPPVVVVVPFFFFFFPPPPPPPPPTTTTTVVVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTVVVRDTTTTMMMMMMMMMMM', //  64
    'OOOOOOOOOOOOOOOOOOOOOPPPPFFFFPPPPPPFFMMPPPPPPPPPPPPPPPPPPPPPPPMMMMFMFMPMMMMMMMMMPPPPVVVVVPFFFFFFPPPPPPTTTTTTTTTTTVVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTPPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTTTDDDRRTTTTTMMMMMMMMMMM', //  65
    'OOOOOOOOOOOOOOOOOOOOOPPPFFFFFFPPPPPPPMMMPPPPPPPPPPPPPPPPPPPPPPPPFFFFMFPMMMMMMMMPPPPVVVVVVPPFFFFPPPPPPPPPTTTTTTTTTTVVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTTPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTTTVDRVTTTTTTTTMMMMMMMMMMM', //  66
    'OOOOOOOOOOOOOOOOOOOOOPPFFFFFFFFPPPPSPMMPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFFFPPPMMMPPPPPPVVVVVVPPPPPPPPPPPPPTTTTTTTTTTTTTVVVVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTTTVVRRTTTTTTTTTTMMMMMMMMMMM', //  67
    'OOOOOOOOOOOOOOOOOOOOOPPFFFFFFFFPPPPPPMMPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFFFPPPPPPPPPPPPVVVVVVPPPPPPPPPPPPPTTPTTTTTTTTTTTVVVVDVTTTTTTTTTTTTTTTTTTTTTTTTTPTTTPTPPPPPPRPPPPPPPPPPPPPPPPPPPPTTTVVTRRTTTTTTTTTTTMMMMMMMMMMM', //  68
    'OOOOOOOOOOOOOOOOOOOOOPPFFFFFFFFPPPPPPMMPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFFFPPPPPPPPPPPPVVVVVPPPPPPPPPPPPPPPPPTTTTTTTTTTTTVVVDVVVTTTTTTTTTTTTTTTTTTTTTTTPTPTTPPPPPPPRPPPPPPPPPPPPPPPPPPPVVVVTTRRTTTTTTTTTTTTMMMMMMMMMMM', //  69
    'OOOOOOOOOOOOOOOOOOOOOPPFFFFFFFFPPPPPPMMPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFFFPPPPPPPPPPPPVVVVVPPPTTPPPPPPTPPPTTTTTTTTTTTTTTTTVDVVVVTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPPPRPPPPPPPPPPPPPPPPPPVVVTTTRRTTTTTTTTTTTTTMMMMMMMMMMM', //  70
    'OOOOOOOOOOOOOOOOOOOOOPPPFFFFFFPPPPPPPMMPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFPPPPPPPPPRRRRDDDRDRRRRRRRRRRTPPPPTPPTTTTTTTTRRRRRRRDDDDRDRRRRRRRRRRRRRRTTTTTTPTPPPPPPPPPPRPPPPPPPPPPPPPPPPVVVVTTTRRTTTTTTTTTTTTTVMMMMMMMMMMM', //  71
    'OOOOOOOOOOOOOOOOOOOOOPPPPFFFFPPPPPPPPMPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFPPPPPPPPPRRPPPVVVVTPTTTTTTPTRRTPPPTPTTTPTTTTRRTTTTTTVVVVVVVTTTTTTTTTTTTRRPTTTTTPPPPPPPPPPPRPPPPPPPPPPPPPPVVPPPPTTRRTTTTTTTTTTTVTVVMMMMMMMMMMM', //  72
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFPPPPPPPTPPPPPPRRPPPPVTTVTPTTTTTTTTTRRTPTPPPTPTTTTRRTTTTTTTTTTVVVVVTTTTTTTTTTTTRRPPPTTPPPPPPPPPPPRPPPPPPPPPPPPPPPPPPPPTRRTTTTTTTTTTTVVVTVMMMMMMMMMMM', //  73
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFPPPTPTPPTPTPRRTPPTVVTVTTTTTTTTTTTTTRRRRRRRRRRRRRRTPTTTTTTTTTVVVVVTTTTTTTTTTTTPRRPPTPPPPPPPPPPPPRPPPPPPPPPPPPPPRRRRRRRRTTTTTTTTTTTVVVTTTMMMMMMMMMMM', //  74
    'OOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVPPFFFFTFTFPPPPPTTPTPRRTPPPPTTVTTTTTTTTTTTTTTTTTPTTPPTPPPPTTPTTTTTTTTTTVVVVTTTTTTTTTTTTTTRRPPPPPPPPPPPPPPRPPPPPPPPPPPPPRRPPPPPTTTTTTTTTTTVVTTTTTMMMMMMMMMMMM', //  75
    'OOOOOOOOOOOOOOOOOOOOOPPPPFFFFPPPPPPPPPPPPPPPPPPPPPPPPVVVPFFTTTFTFPTTPPTTTTPRTPPTPPTVTTTTTTTTTTTTTTTTTTTTPPPPPPPTTPTPTTPTTTTTTTVVVVTTTTPTTTTPTTPTRRRRRRRRRRRPPPPRPPPPPPPPPPTTRRPPPPPPTTTTTTTVTVVTTTTTTTTMMMMMMMMMMM', //  76
    'OOOOOOOOOOOOOOOOOOOOOPPPFFFFFFPPPPPPPPPPPPPPPPPPPPPPPVVVVVTFTTFTTPTPTTPTTTTRTPTTPTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPTPPPPTTPTTTTTTTVVVVTTTTTPTTPTPTPTPPPPPPPPPPRRPPPRPPPPPPPPPTTRRTTPPPPPTTTTTTVVVTTTTTTTTTTMMMMMMMMMMM', //  77
    'OOOOOOOOOOOOOOOOOOOOOPPPFFFFFFPPPPPPPPPPPPPPPPPPPPPPPVVVVVVVFTTTTTTTTTTTTTRRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPTTTPPTTTTTTTTVVVFTTTTTTTTPTTPTTPPPPPPPPPPRRPPRPPPPPPPPTTRRTTTTPPPPTTTTTVVVTTTTTTTTTTTMMMMMMMMMMM', //  78
    'OOOOOOOOOOOOOOOOOOOOOOPPFFFFFFPPPPPPPPPHHHPPPPPPPPPPPPPVVVVVVVTTTTTTTTTTTRRTTPTTTTVTTTTTTTTTTTTTTTTTTTTTPPPPPPPPPPPPTPTPTTTTTTTVVVVVTTTPTPTPTPTTTPPPPPPPPPPPRRPRPPPPPPPTTRRTTTTTTPPPTVVVVTTTTTTTTTTTTTMMMMMMMMMMMP', //  79
    'OOOOOOOOOOOOOOOOOOOOOPOPFFFFFFPPPPPFFFFHHHPPPPPPPPPPPPPPVVVVVVVTTTTTTTTTRRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPPTTPTTPTTTTTTTTVVVVTTTTTTTTTTTTTPTFFFPPPPPPPRRRPPPPPPPTRRTTTTTTPPPPVVVVTTTTTTTTTTTTTTMMMMMMMMMMMP', //  80
    'OOOOOOOOOOOOOOOOOOOOOOPPPFFFFPPPPFFFFFHHHHPPPPPPPPPTPPPPTVTVVVVDVTTTTTTRRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPTPTTTTTTTTTTTTTTVVVTTTTTTTTTTTPTTTTFFFFPPPPPPRRPPPPPPPRRTTTTTTPVVVVVVVTTTTTTTTTTTTTTTMMMMMMMMMMMP', //  81
    'OOOOOOOOOOOOOOOOOOOOOOPPPSSSPPPPFHHHHHHHFFPPPPPPPPPPTTTTTTTVVVVDVTTTTTRRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTPPPPPTTTTTTTTTTTTTTTTTTTTVVVTTTTTTTTTTTTFTFTFTFFPPPPPPRRRRRRRRRTTTTTTPVVVVPTTTTTTTTTTTTTTTTTVMMMMMMMMMMMP', //  82
    'OOOOOOOOOOOOOOOOOOOOOOOPSSSSSSPPFHHHHHHHFFPPPPPPPPPTPTTTTTTTTVVDVVVVTRRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTFFTFFTFPPPPPPPPPPPPPPTTTTTTTVVVVPPTTTTTTTTTTTTTTTTVVMMMMMMMMMMMP', //  83
    'OOOOOOOOOOOOOOOOOOOOOOOSSSSSSSPFFHHHHHHFFFFPPPPPPPPPPPTTTTTTTTVDVVVVRRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFTFPPPTPPTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTTTTFFTFFPPPPPPPPPPPPPPTTTTTPPPPPPPTTTTTTTTTTTTVTVVVVMMMMMMMMMMMP', //  84
    'OOOOOOOOOOOOOOOOOOOOOOOSSSSSSPPFFHHHHHFFFFFPPPPPPPTPTTTTTTRRRRRRRDDDDTTTTTTTTTTTTTTTTTTVTTTTTTTTTTTTFFTTPPPPPTTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTTTFTFTFPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTVVVVVTVTMMMMMMMMMMMP', //  85
    'OOOOOOOOOOOOOOOOOOOOOOOSSSSSPPPFFHHHHHFFFFFPPPPPPPTTTTTTTRRTTTTTTVVVVTTTTTTTTTTTTTTTTTTTVTTPTPTPPTFTTFFPPPPPTTTTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTTTFFFFPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTVVVVTTTTTMMMMMMMMMMPP', //  86
    'OOOOOOOOOOOOOOOOOOOOOOOSSSSSSPPFFHHHHHFFFFFPPPPPPPPTTTTTRRTTTTTTTTVVVVTTTTTTTTTTTTTTTTVTTTPTTTPTTFFFFFFPPPPPTPTTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTTTTFFFPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTVVVTTTTTTMMMMMMMMMMMPP', //  87
    'OOOOOOOOOOOOOOOOOOOOOOOPSSSSSPPPFHHHHHFFFFPPPPPPPPTPPTTRRTTTTTTTTTTVVVVTTTTTTTTTTTTTTTTVTPPTPPPPPTFTFFPPTPPPTTTTTTTTTTTTTTTTTTTTTTTTTVVVTTTTTTTTTTTTTTTFFPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTVVVTTTTTTTTMMMMMMMMMMMPP', //  88
    'OOOOOOOOOOOOOOOOOOOOOOOPSSSSSSPPFHHHHHFFFFPPPPPPPPPTTTRRTTTTTTTTTTTTVVVTTTTTTTTTTTTTTTVTTVPPPPPPPPPPPPPPPPTPTPTTTTTTTTTTTTTTTTTTTTTTVVVVVTTTTTTTTTTTTTTTFPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTVVVTTTTTTTTTMMMMMMMMMMMPP', //  89
    'OOOOOOOOOOOOOOOOOOOOOOOPSSSSSSPPPHHHHHHFFPPPPPRRRRRRRRRTTTTTTTTTTTTTTVVVTTTTTTTTTTTTTVTVVVPPPPPPPPPPPPPPPPTPTTTTTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTFTTTPPPPPPPPPPPPPPPPPPPPPPPPPTTVVVVVTVTTTTTTTTTTMMMMMMMMMMMPP', //  90
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHHPPPPPRRPPPTPTTTTTTTTTTTTTTTTTVVVTTTTTTTTTTTTTTTVVTPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTTTFPPPPPPPPPPPPPPPPPPPPPPPPPTVVVVTTTTTTTTTTTTTTMMMMMMMMMMMPP', //  91
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHHPPPPRRPPPPPPPPPTTTTTTTTTTTTTTTVVVVTTTTTTTTTTTTVVVVPPPPPPPPPPPPPPPPTPTTTTTTTTTTTTTTTTTTTTTTTTTTVVVVVTTTTTTTTTTTFTFFPPPPPPPPPPPPPPPPPPPPPPPPVVVVTTTTTTTTTTTTTTTMMMMMMMMMMMPP', //  92
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHHPPPRRPPPPPPTPPTTTTTTTTTTTTTTTTDDDDTTTTTTTTPTTVVVVVVPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTTFTTFFPPPPPPPPPPPPPPPPPPPPPVVVPTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMP', //  93
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHHPPRRPPPPPPPPTPPTTTTTTTTTTTTTTTTVVVVTTTTTTTPPPVVVVVVPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTTVVVVVTTTTTTTTTFTFTFPPPPPPPPPPPPPPPPPPPPVVPPPPTTTTTTTTTTTTTTTVVMMMMMMMMMMMPP', //  94
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHFPPRPPPPPPPPPPPPPTTTTTTTTTTTTTTTTVVVTTTTTTPTTPPTDDDDPPPPPPPPPPPPPPPTPTPTTTTTTTTTTTTTTTTTTTTTTTTTTTVVVTTTTTTTTTTTFFFPPPPPPPPPPPPPPPPFFHFHPHPPPTTTTTTTTTTTTTVVVVMMMMMMMMMMMPP', //  95
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHFPPPPPPPPPPPPPPPPTTTTTPTTTTTTTTTTVVVVTTTTPTPPPPVVVDVPPPPPPPPPPPPPPPPPTPTTTTTTTTTTTTTTTTTTTTTTTTTTTVVVTTTTTTTPTTFFFPPPPPPPPPPPPPPPFHHHHFHHPHPPTTTTTTTTTTVTVVVVTMMMMMMMMMMMPP', //  96
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHFPPPPPPPPPPPPPPPPPPPPTPTPTTTTTTTTVVVVTTTTPPPPPPVVVDVPPPPPPPPPPPPPPPPPPPTPTTTTTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTTTPTPPPPPPPPPPPPPPPPFFHHHFHHHHPHPHTTTTTTTTVVVVVVTTMMMMMMMMMMMPP', //  97
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHFFFFFFFFPPPPPPPPPPPPPPTPPPTPPTTPTTPPTPTVVVVTPTTTTPPPVVVDVVPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTTTTTVVVTTTTPTTTPTPTPPPPPPPPPPPPPPPPFFFHHHHHHHHHHTTTTTTVTVVVTTTTTTMMMMMMMMMMMPP', //  98
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPFFFFFFFFFPPPPPPPPPPPPPPPPPPTTTPTPPPPTTTPTVTFTPPPPPPPPVVDVVPPPPPPPPPPPPPPPPPTTPTTPTTTTTTTTTTTTTTTTTTTTVVVVTTTTTTTPTPPPTTPPPPPPPPPPPPPFHFHHHHHHHHHHHTTTTTVVVVTTTTTTTTMMMMMMMMMMMPP', //  99
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPTPPPTPTPPFFTFFFTPPPPPPPVVDVVPPPPPPPPPPPPPPPPPPPTPPTPTTTPTTTTTTTTTTTTTTTVVVVTTTTTPPTPPPTTTTPPPPPPPPPPPPFFHHHHHHHHHHHHTHVTVVVTTTTTTTTTTMMMMMMMMMMMPP', // 100
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPTPPPTPPFTFFFFPPPPPPPPVVDVVPPPPPPFFFFPPPPPPPPPPPTTPTTTTTTTPTTTTTTTTTTTVVVPPTTPPTPPPPPTTTTPPPPPPPPPPPPFHHHHHHHHHHHHHHVVVVTTTTTTTTTTTTMMMMMMMMMMMPP', // 101
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFPPPPPPPPPVDVVVPPPPFFFFFFPPPPPPPPPPPPPTPTTTTTPPTPTTTPTTTVVVVVPPPPPPPPPPPPTTPPPPPPPPPPPPPHFHHHHHHHHHHHHVVVTTTTTTTTTTTTTTMMMMMMMMMMMPP', // 102
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFPPPPPPPPPVDVVVPPPFFFFFFFFPPPPPPPPPPPPTPPPTTTTTPTPPTPPTPVVVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHHHHHHHHVVVVHHTTTTTTTTTTTTTTMMMMMMMMMMMMPP', // 103
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFPPPPPPPPPPVDVVVPPPFFFFFFFFPPPPPPPPPPPPPPTPPPPPTTTPPPTPTPDDDDTPTPPPPPPPPPPPPPPPPPPPPPPPPPPFHFHHHHHVVVHPHTTTTTTTTTTTTTTTMMMMMMMMMMMMPP', // 104
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVDVVVPPPFFFFFFFFPPPPPPPPPPPPPPPPPTHHHHTPPHHHPHVVVHPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFHHHHHVVVHPHTTTTTTTTTTTTTTTTMMMMMMMMMMMMPP', // 105
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVDVVVPPPFFFFFFFFPPPPPPPPPPPPPPHHHHHHHHHHHHHHHVVVVHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPHFHHPPHHHPTTTTTTTTTTTTVTVVMMMMMMMMMMMPPP', // 106
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVDVVPPPPPFFFFFHHHHHHHHHPPPPPPPHHHHHHHHHHHHHHHVVVVHHHHHHHHHHHHHHPHHHHHHPHPPPPPPPPPPPPHHHPPPPPTTTTTTTTTTTVVVVMMMMMMMMMMMMMPP', // 107
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVDVVHPHHHHHHHHHHHHHHHHHPPPPPPPHHHHHHHHHHHHHHHVVVHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPHHHHPPPPPPPPPTTTTTTTTTTVVVTTMMMMMMMMMMMMMPP', // 108
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVDVVHHHHHHHHHHHHHHHHHHHPPPPPPPHHHHHHHHHHHHHHVVVVHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPPTTTTTTTVVVVVTTTMMMMMMMMMMMMMPP', // 109
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHVVDVVHHHHHHHHHHHHHHHHHHHPPPPPPPHHHHHHHHHHHHHHVVVVVHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPTTTTVVVVVTVTTTTTMMMMMMMMMMMPPP', // 110
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHVVDVVHHHHHHHHHHHHHHHHHHHPPPPPPPHHHHHHHHPPPHHHVVVVHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPTTTVVVVVTTTTTTTTMMMMMMMMMMMPPP', // 111
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHHVVDVVHHHHHHHHHHHHHHHHHHHPPPPPPPHHPPPPPPPPPPPVVVVPPPHHHHHHPPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPTTVVVVVTTTTTTTTTMMMMMMMMMMMPPP', // 112
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHVVDVVHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPVVVVPPPPPPPPPPPPPPPHPHHHHHHPHHHHHHHHHHHHHHHHHHHPPVVTTVTTTTTTTTTTTMMMMMMMMMMMPPP', // 113
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHHVVDVVHPHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVVVPPPPPPPPPPPPPPPPPPPPPPPPPPHHHPPPHHHHHHHHHHVVVTTTTTTTTTTTTTTTTMMMMMMMMMMMPPP', // 114
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVDVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPHVVVVPPTTTTTTTTTTTTTTTMMMMMMMMMMMMMPP', // 115
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVDVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVVPPPPTTTTTTTTTTTTTTTMMMMMMMMMMMMMPP', // 116
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVVDVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVPPPPPTTTTTTTTTTTTTTVVMMMMMMMMMMMPPP', // 117
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOPFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVVDVVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTVVVVTVMMMMMMMMMMMPPP', // 118
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVVDVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTVVVVTTTMMMMMMMMMMMPPP', // 119
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFPPPPPDDDDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTVVVVTTTMMMMMMMMMMMPPPP', // 120
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFPPPPVVVDVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTVVVTVTTTTTMMMMMMMMMMMPPPP', // 121
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOPFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFFFPPPVVVDVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFTTVTVVVVTTTTTTTMMMMMMMMMMMPPPP', // 122
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOPFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFFFPPPVVVDVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFTVVVTVVTTTTTTTTMMMMMMMMMMMPPPP', // 123
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFFFFFFFFPPPVVVDVPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVVVTTTTTTTTTTTTMMMMMMMMMMMPPPP', // 124
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSVVVDVSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVPVVVTTTTTTTTTTTTTTMMMMMMMMMMMMMPPP', // 125
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSVVVVDVSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVVVPPTTTTTTTTTTTTTTTMMMMMMMMMMMPPPP', // 126
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSVVVVDSSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPVVPPPPTTTTTTTTTTTTTTTMMMMMMMMMMMPPPP', // 127
    'OOOOOOOOOOOOOOOOOOOOOPOOOPOOOOPOPOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSVVVVDSSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTMMMMMMMMMMMPPPP', // 128
    'OOOOOOOOOOOOOOOOOOOOOOPOPOOPOPOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSVVVDDSSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTMMMMMMMMMMMPPPP', // 129
    'OOOOOOOOOOOOOOOOOOOOOPOOOPOOPPPPPOPOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSVVDDVSSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTMMMMMMMMMMMPPPP', // 130
    'OOOOOOOOOOOOOOOOOOOOOPPOOOOOPPOOPPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSVVDVVVSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTMMMMMMMMMPPPPP', // 131
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSVVVVVVSSSSSSSSSSSSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMPPPPP', // 132
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPOPPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSSSOSVVVVVVSOOSSSSSSSOSSSSSSSPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMPPPPPP', // 133
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPSSSSSSSSSOSSSVVVVVVSSSOSSSSSSSSSOSSSSPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMPPPPPP', // 134
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOSSSOSSSOSOSSOOVVVVVVOOSOSSSOOSOSOSSSSPOOPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMPPPPPPPP', // 135
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOOSOOOSOOSOOSSOOOVVVVVOOSOOSOOOOOSOOOSOOOOPOOPOPOPOPPPPPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 136
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOOOOOOOSOOOOOOOVVVVVOOOOOOOOOOSOOOSOOOOPPOOPOOPOPPPPPOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 137
    'OOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPOOOSOOOOOOSOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPOPOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP', // 138
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPFFOFPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 139
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPFOFFFFPPPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 140
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFPPPOOPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 141
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPFFFFFFFFPPPPPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 142
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPFFFFFFFFPPPPPPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 143
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFFFFFPPPPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 144
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOPFFFFFFPPPPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 145
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOFFFFPPPPOPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 146
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOPOPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 147
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPOPPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 148
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', // 149
  ],
  cities: [
    { id: 'angband', name: '安格班', x: 98, y: 4, size: 'capital', owner: 8,
      produces: ['orc_foot', 'boldog_guard', 'troll', 'dragon'] },
    { id: 'thangorodrim', name: '桑戈洛锥姆', x: 108, y: 5, size: 'city', owner: 8,
      produces: ['orc_foot', 'orc_archer', 'troll'] },
    { id: 'iron_gate', name: '铁山南门', x: 84, y: 8, size: 'town', owner: 8,
      produces: ['orc_foot', 'warg_rider'] },
    { id: 'east_gate', name: '铁山东门', x: 144, y: 8, size: 'town', owner: 8,
      produces: ['orc_foot', 'orc_archer'] },
    { id: 'west_camp', name: '西方的兽人营', x: 45, y: 14, size: 'village', owner: 8,
      produces: ['orc_foot'] },
    { id: 'ard_camp', name: '阿德加兰哨站', x: 126, y: 22, size: 'village', owner: 0,
      produces: ['orc_foot'] },
    { id: 'eithel_sirion', name: '巴拉德埃塞尔', x: 75, y: 33, size: 'capital', owner: 1,
      produces: ['noldor_sword', 'sindar_archer', 'hithlum_horse', 'hithlum_lance'] },
    { id: 'mithrim', name: '米斯林', x: 47, y: 37, size: 'city', owner: 1,
      produces: ['edain_militia', 'noldor_sword', 'hithlum_horse'] },
    { id: 'dor_lomin', name: '多尔洛明', x: 42, y: 52, size: 'city', owner: 1,
      produces: ['edain_militia', 'hithlum_horse', 'noldor_sword'] },
    { id: 'hithlum_watch', name: '希斯路姆北哨', x: 60, y: 29, size: 'town', owner: 1,
      produces: ['noldor_sword', 'sindar_archer'] },
    { id: 'annon_gelydh', name: '诺多之门', x: 36, y: 61, size: 'town', owner: 0,
      produces: ['edain_militia', 'falas_sailor'] },
    { id: 'vinyamar', name: '维尼阿马', x: 26, y: 68, size: 'town', owner: 0,
      produces: ['falas_sailor', 'sindar_archer'] },
    { id: 'brithombar', name: '布砾松巴', x: 36, y: 85, size: 'city', owner: 6,
      produces: ['falas_sailor', 'sindar_archer', 'noldor_sword'] },
    { id: 'eglarest', name: '埃格拉瑞斯特', x: 38, y: 104, size: 'capital', owner: 6,
      produces: ['falas_sailor', 'sindar_archer', 'noldor_sword', 'hithlum_horse'] },
    { id: 'falas_watch', name: '法拉斯南望', x: 41, y: 120, size: 'village', owner: 6,
      produces: ['falas_sailor'] },
    { id: 'balar', name: '巴拉尔岛', x: 57, y: 142, size: 'town', owner: 0,
      produces: ['falas_sailor', 'sindar_archer'] },
    { id: 'gondolin', name: '刚多林', x: 63, y: 52, size: 'capital', owner: 4,
      produces: ['gondolin_guard', 'noldor_sword', 'sindar_archer', 'eagle'] },
    { id: 'crissaegrim', name: '克瑞赛格林', x: 75, y: 46, size: 'village', owner: 0,
      produces: ['eagle'] },
    { id: 'ladros', name: '拉德洛斯', x: 132, y: 25, size: 'town', owner: 0,
      produces: ['edain_militia', 'haladin_axe'] },
    { id: 'tarn_aeluin', name: '塔恩埃路因', x: 111, y: 33, size: 'town', owner: 0,
      produces: ['edain_militia', 'sindar_archer'] },
    { id: 'dorthonion_hold', name: '多松尼安要塞', x: 96, y: 27, size: 'town', owner: 1,
      produces: ['noldor_sword', 'sindar_archer'] },
    { id: 'aglon', name: '阿格隆隘口', x: 147, y: 30, size: 'town', owner: 2,
      produces: ['feanor_warrior', 'noldor_sword'] },
    { id: 'sirion_pass', name: '西瑞安隘口哨所', x: 83, y: 38, size: 'town', owner: 1,
      produces: ['noldor_sword', 'hithlum_horse'] },
    { id: 'tol_sirion', name: '西瑞安河心岛', x: 86, y: 52, size: 'town', owner: 3,
      produces: ['noldor_sword', 'sindar_archer'] },
    { id: 'nargothrond', name: '纳国斯隆德', x: 66, y: 85, size: 'capital', owner: 3,
      produces: ['noldor_sword', 'galadhrim_bow', 'sindar_archer', 'hithlum_horse'] },
    { id: 'taur_faroth', name: '陶尔恩法罗斯', x: 60, y: 76, size: 'town', owner: 3,
      produces: ['galadhrim_bow', 'sindar_archer'] },
    { id: 'brethil', name: '布瑞希尔', x: 93, y: 78, size: 'city', owner: 0,
      produces: ['haladin_axe', 'sindar_archer', 'edain_militia'] },
    { id: 'amon_obel', name: '阿蒙欧贝尔', x: 99, y: 85, size: 'village', owner: 0,
      produces: ['haladin_axe'] },
    { id: 'amon_rudh', name: '阿蒙鲁兹', x: 75, y: 101, size: 'village', owner: 0,
      produces: ['edain_militia'] },
    { id: 'nan_tathren', name: '南塔斯仁', x: 78, y: 123, size: 'town', owner: 0,
      produces: ['sindar_archer', 'edain_militia'] },
    { id: 'sirion_havens', name: '西瑞安河口', x: 81, y: 131, size: 'city', owner: 0,
      produces: ['falas_sailor', 'edain_militia', 'sindar_archer'] },
    { id: 'menegroth', name: '明霓国斯', x: 126, y: 79, size: 'capital', owner: 5,
      produces: ['doriath_warden', 'sindar_archer', 'noldor_sword', 'galadhrim_bow'] },
    { id: 'neldoreth', name: '涅尔多瑞斯林哨', x: 126, y: 60, size: 'city', owner: 5,
      produces: ['doriath_warden', 'sindar_archer'] },
    { id: 'region', name: '瑞吉安林哨', x: 132, y: 95, size: 'city', owner: 5,
      produces: ['doriath_warden', 'sindar_archer'] },
    { id: 'esgalduin_ford', name: '埃斯加尔都因渡口', x: 117, y: 71, size: 'town', owner: 5,
      produces: ['doriath_warden', 'sindar_archer'] },
    { id: 'aelin_uial', name: '埃林尤伊尔', x: 99, y: 104, size: 'town', owner: 0,
      produces: ['sindar_archer', 'edain_militia'] },
    { id: 'himring', name: '希姆凛', x: 158, y: 40, size: 'capital', owner: 2,
      produces: ['feanor_warrior', 'noldor_sword', 'sindar_archer', 'hithlum_horse'] },
    { id: 'maglor_gap', name: '迈格洛尔缺口', x: 150, y: 27, size: 'town', owner: 2,
      produces: ['feanor_warrior', 'hithlum_horse'] },
    { id: 'himlad', name: '希姆拉德', x: 165, y: 52, size: 'town', owner: 2,
      produces: ['feanor_warrior', 'noldor_sword'] },
    { id: 'estolad', name: '埃斯托拉德', x: 147, y: 85, size: 'city', owner: 0,
      produces: ['edain_militia', 'haladin_axe', 'feanor_warrior'] },
    { id: 'amon_ereb', name: '阿蒙埃瑞布', x: 171, y: 100, size: 'city', owner: 2,
      produces: ['feanor_warrior', 'edain_militia', 'noldor_sword'] },
    { id: 'thargelion', name: '沙盖理安', x: 180, y: 46, size: 'town', owner: 2,
      produces: ['feanor_warrior', 'edain_militia'] },
    { id: 'ramdal', name: '拉姆达尔', x: 183, y: 112, size: 'village', owner: 0,
      produces: ['edain_militia'] },
    { id: 'ossir_north', name: '欧西瑞安德北林', x: 186, y: 65, size: 'town', owner: 0,
      produces: ['galadhrim_bow', 'sindar_archer'] },
    { id: 'ossir_south', name: '欧西瑞安德南林', x: 189, y: 104, size: 'town', owner: 0,
      produces: ['galadhrim_bow', 'sindar_archer'] },
    { id: 'belegost', name: '贝烈国斯特', x: 195, y: 55, size: 'capital', owner: 7,
      produces: ['dwarf_heavy', 'dwarf_axe', 'dwarf_mask', 'noldor_sword'] },
    { id: 'nogrod', name: '诺格罗德', x: 197, y: 85, size: 'capital', owner: 7,
      produces: ['dwarf_heavy', 'dwarf_axe', 'dwarf_mask'] },
    { id: 'dwarf_road', name: '矮人大道驿站', x: 186, y: 71, size: 'village', owner: 7,
      produces: ['dwarf_axe'] },
    { id: 'mount_dolmed', name: '多尔梅德山口', x: 198, y: 70, size: 'town', owner: 7,
      produces: ['dwarf_heavy', 'dwarf_axe'] },
    { id: 'lothlann', name: '洛斯兰边营', x: 168, y: 20, size: 'village', owner: 0,
      produces: ['orc_foot', 'warg_rider'] },
    { id: 'androth', name: '安德洛斯洞窟', x: 50, y: 45, size: 'village', owner: 0,
      produces: ['sindar_archer'] },
    { id: 'ivrin', name: '伊芙林泉', x: 66, y: 68, size: 'town', owner: 0,
      produces: ['sindar_archer', 'edain_militia'] },
    { id: 'brithiach', name: '布砾希阿赫', x: 92, y: 63, size: 'village', owner: 0,
      produces: ['edain_militia'] },
    { id: 'barad_nimras', name: '巴拉德宁拉斯', x: 35, y: 95, size: 'town', owner: 6,
      produces: ['falas_sailor', 'sindar_archer'] },
    { id: 'arossiach', name: '阿洛斯渡口镇', x: 146, y: 57, size: 'village', owner: 0,
      produces: ['sindar_archer'] },
    { id: 'thalos_vale', name: '沙洛斯河谷', x: 182, y: 76, size: 'village', owner: 0,
      produces: ['galadhrim_bow'] },
    { id: 'tol_galen', name: '托尔加兰', x: 182, y: 123, size: 'town', owner: 0,
      produces: ['galadhrim_bow', 'sindar_archer'] },
    { id: 'taras', name: '塔拉斯山麓', x: 26, y: 78, size: 'village', owner: 0,
      produces: ['falas_sailor', 'edain_militia'] },
    { id: 'dor_dinen', name: '多尔迪能哨所', x: 134, y: 50, size: 'village', owner: 0,
      produces: ['sindar_archer'] },
    { id: 'estolad_south', name: '埃斯托拉德南屯', x: 150, y: 93, size: 'village', owner: 0,
      produces: ['edain_militia', 'haladin_axe'] },
  ],
  features: [
    { type: 'ruin', x: 46, y: 17, name: '阿德加兰的坟丘' },
    { type: 'ruin', x: 138, y: 16, name: '铁山脚的地窖' },
    { type: 'ruin', x: 105, y: 46, name: '多松尼安的石环' },
    { type: 'ruin', x: 54, y: 65, name: '希斯路姆的旧塔' },
    { type: 'ruin', x: 81, y: 90, name: '纳洛格河畔的废墟' },
    { type: 'ruin', x: 108, y: 120, name: '长墙下的墓室' },
    { type: 'ruin', x: 162, y: 63, name: '东境的碑林' },
    { type: 'ruin', x: 192, y: 120, name: '欧西瑞安德的祭石' },
    { type: 'ruin', x: 33, y: 112, name: '海岸的沉船窟' },
    { type: 'ruin', x: 144, y: 106, name: '阿蒙埃瑞布的地穴' },
    { type: 'ruin', x: 69, y: 131, name: '沼泽中的塔基' },
    { type: 'ruin', x: 177, y: 27, name: '缺口北的哨堡遗址' },
    { type: 'temple', x: 89, y: 59, name: '西瑞安的祭坛' },
    { type: 'temple', x: 45, y: 82, name: '海畔的祭坛' },
    { type: 'temple', x: 138, y: 49, name: '多瑞亚斯北境的祭坛' },
    { type: 'temple', x: 174, y: 85, name: '七河之间的祭坛' },
    { type: 'temple', x: 66, y: 109, name: '南方的祭坛' },
    { type: 'temple', x: 156, y: 19, name: '缺口的祭坛' },
    { type: 'sage', x: 60, y: 95, name: '纳洛格的先知' },
    { type: 'sage', x: 129, y: 85, name: '明霓国斯的智者' },
    { type: 'sage', x: 189, y: 60, name: '矮人的匠师' },
    { type: 'sage', x: 93, y: 128, name: '河口的观星者' },
    { type: 'ruin', x: 90, y: 16, name: '铁山南麓的坑道' },
    { type: 'ruin', x: 45, y: 90, name: '法拉斯的古灯塔' },
    { type: 'temple', x: 102, y: 90, name: '布瑞希尔的祭坛' },
    { type: 'sage', x: 162, y: 46, name: '希姆凛的星象师' },
  ],
  garrisons: {},
  players: [1, 2, 3, 4, 5, 6, 7, 8],
};
